### ISSUE TITLE
Setup ESLint and Prettier for TypeScript

### ISSUE THREAD

**Issue by BrianEmilius** [BrianEmilius/robust-express-app#6]
The project needs linting.

We'd like to use ESLint and Prettier to automatically lint typescript as well as any vanilla js files.

Ideally, the linter would prevent git commits on lint fails.

**Comment by nikoheikkila** [comment]
I could take a look at this to practice my JS project skills.

Sounds like we need to include ESLint, Prettier, and Husky into the project as dependencies and have Husky run something like `npm run lint` before each commit? I could also provide an example ruleset which we can discuss.

**Comment by BrianEmilius** [comment]
Sounds great @nikoheikkila 
Yep, eslint, prettier and husky would do the trick.

An example ruleset would be perfect 👍
