### ISSUE TITLE
Documentation with TypeDoc

### ISSUE THREAD

**Issue by BrianEmilius** [BrianEmilius/robust-express-app#7]
The project needs documentation on all existing TypeScript modules and functions.
Use TypeDoc and gulp-typedoc and build documentation files in `/docs`.

**Comment by faergeek** [comment]
@BrianEmilius Hi! Does anybody work on this already? Not sure why it's reopened. If nobody works on it, then I'd like to :-)

**Comment by BrianEmilius** [comment]
Hey @faergeek 
It's up for grabs for sure. I just closed it to edit it and then opened it once I had formed a better description of what was needed.
Looking forward to your solution :smile:

**Comment by faergeek** [comment]
I'm not sure that I'll have enough spare time for this very soon. If anybody would like to take on, please do so :-)
