### ISSUE TITLE
Implement request caching

### ISSUE THREAD

**Issue by BrianEmilius** [BrianEmilius/robust-express-app#8]
All requests of the GET method should be cached. 
Use the npm package `memory-cache` in a custom middleware function.

**Comment by onlywicked** [comment]
I would like to work on this issue.

**Comment by BrianEmilius** [comment]
Fantastic, @onlywicked 
I look forward to seeing your solution :)

**Comment by onlywicked** [comment]
Sorry for the delay.
I was busy with my internship and college work.
